# NumPy and Pandas Practice
## by Samnit Mehandiratta

### NumPy

In [0]:
import numpy as np

In [0]:
array1 = np.array([1,2,3])
print(array1)
print(array1.dtype)

print(array1[-1::-1])

[1 2 3]
int64
[3 2 1]


In [0]:
a = np.arange(12).reshape(3, 4)
print(a)

rows_on = np.array([True, False, True])
a[rows_on, :]

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


array([[ 0,  1,  2,  3],
       [ 8,  9, 10, 11]])

In [0]:
np.ones((12,12))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [0]:
np.zeros((12,12))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [0]:
np.full((12,12),12)

array([[12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12],
       [12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12],
       [12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12],
       [12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12],
       [12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12],
       [12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12],
       [12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12],
       [12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12],
       [12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12],
       [12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12],
       [12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12],
       [12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12]])

In [0]:
np.arange(12,121,12) # [initial,final) the final number is not included

array([ 12,  24,  36,  48,  60,  72,  84,  96, 108, 120])

In [0]:
np.linspace(1,12,12)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.])

In [0]:
np.random.rand(1,3)

array([[0.74158035, 0.43925371, 0.91435111]])

In [0]:
np.empty((2,3))

array([[4.66769949e-310, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000]])

In [0]:
coeffs  = np.array([[2, 6], [5, 3]])
depvars = np.array([6, -9])
solution = np.linalg.solve(coeffs, depvars)
solution


array([-3.,  2.])

### Pandas

In [0]:
import pandas as pd

In [0]:
people_dict = { "weight": pd.Series([68, 83, 112],
                index=["alice", "bob", "charles"]),
               "birthyear": pd.Series([1984, 1985, 1992], index=["bob", "alice", "charles"], name="year"),
"children": pd.Series([0, 3], index=["charles", "bob"]),
"hobby": pd.Series(["Biking", "Dancing"], index=["alice", "bob"]),}

people = pd.DataFrame(people_dict)
people

weight 
 birthyear 
 children 
 hobby 
 
 
 
 
 alice 
 68 
 1985 
 NaN 
 Biking 
 
 
 bob 
 83 
 1984 
 3.0 
 Dancing 
 
 
 charles 
 112 
 1992 
 0.0 
 NaN

In [0]:
people[people["birthyear"] < 1990]

weight 
 birthyear 
 children 
 hobby 
 
 
 
 
 alice 
 68 
 1985 
 NaN 
 Biking 
 
 
 bob 
 83 
 1984 
 3.0 
 Dancing

In [0]:
iris = pd.read_csv("IRIS.csv")

In [0]:
iris

sepal_length 
 sepal_width 
 petal_length 
 petal_width 
 species 
 
 
 
 
 0 
 5.1 
 3.5 
 1.4 
 0.2 
 Iris-setosa 
 
 
 1 
 4.9 
 3.0 
 1.4 
 0.2 
 Iris-setosa 
 
 
 2 
 4.7 
 3.2 
 1.3 
 0.2 
 Iris-setosa 
 
 
 3 
 4.6 
 3.1 
 1.5 
 0.2 
 Iris-setosa 
 
 
 4 
 5.0 
 3.6 
 1.4 
 0.2 
 Iris-setosa 
 
 
 ... 
 ... 
 ... 
 ... 
 ... 
 ... 
 
 
 145 
 6.7 
 3.0 
 5.2 
 2.3 
 Iris-virginica 
 
 
 146 
 6.3 
 2.5 
 5.0 
 1.9 
 Iris-virginica 
 
 
 147 
 6.5 
 3.0 
 5.2 
 2.0 
 Iris-virginica 
 
 
 148 
 6.2 
 3.4 
 5.4 
 2.3 
 Iris-virginica 
 
 
 149 
 5.9 
 3.0 
 5.1 
 1.8 
 Iris-virginica 
 
 
 
 150 rows × 5 columns

In [0]:
iris.head()

sepal_length 
 sepal_width 
 petal_length 
 petal_width 
 species 
 
 
 
 
 0 
 5.1 
 3.5 
 1.4 
 0.2 
 Iris-setosa 
 
 
 1 
 4.9 
 3.0 
 1.4 
 0.2 
 Iris-setosa 
 
 
 2 
 4.7 
 3.2 
 1.3 
 0.2 
 Iris-setosa 
 
 
 3 
 4.6 
 3.1 
 1.5 
 0.2 
 Iris-setosa 
 
 
 4 
 5.0 
 3.6 
 1.4 
 0.2 
 Iris-setosa

In [0]:
iris.tail()

sepal_length 
 sepal_width 
 petal_length 
 petal_width 
 species 
 
 
 
 
 145 
 6.7 
 3.0 
 5.2 
 2.3 
 Iris-virginica 
 
 
 146 
 6.3 
 2.5 
 5.0 
 1.9 
 Iris-virginica 
 
 
 147 
 6.5 
 3.0 
 5.2 
 2.0 
 Iris-virginica 
 
 
 148 
 6.2 
 3.4 
 5.4 
 2.3 
 Iris-virginica 
 
 
 149 
 5.9 
 3.0 
 5.1 
 1.8 
 Iris-virginica

In [0]:
iris.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   species       150 non-null    object 
dtypes: float64(4), object(1)
memory usage: 6.0+ KB


In [0]:
iris.describe

<bound method NDFrame.describe of      sepal_length  sepal_width  petal_length  petal_width         species
0             5.1          3.5           1.4          0.2     Iris-setosa
1             4.9          3.0           1.4          0.2     Iris-setosa
2             4.7          3.2           1.3          0.2     Iris-setosa
3             4.6          3.1           1.5          0.2     Iris-setosa
4             5.0          3.6           1.4          0.2     Iris-setosa
..            ...          ...           ...          ...             ...
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

[150 rows x 5 columns]>

In [0]:
petalLengthSeries = pd.Series(iris["petal_length"])

petalLengthSeries[petalLengthSeries>2]

50     4.7
51     4.5
52     4.9
53     4.0
54     4.6
      ... 
145    5.2
146    5.0
147    5.2
148    5.4
149    5.1
Name: petal_length, Length: 100, dtype: float64

In [0]:
petalLengthSeries.iloc[5]

1.7

In [0]:
petalLengthSeries.head(10)

0    1.4
1    1.4
2    1.3
3    1.5
4    1.4
5    1.7
6    1.4
7    1.5
8    1.4
9    1.5
Name: petal_length, dtype: float64

In [0]:
petalLengthSeries[-1::-1]

149    5.1
148    5.4
147    5.2
146    5.0
145    5.2
      ... 
4      1.4
3      1.5
2      1.3
1      1.4
0      1.4
Name: petal_length, Length: 150, dtype: float64

In [0]:
petalLengthSeries.astype(int)

0      1
1      1
2      1
3      1
4      1
      ..
145    5
146    5
147    5
148    5
149    5
Name: petal_length, Length: 150, dtype: int64

In [0]:
petalLengthSeries

0      1.4
1      1.4
2      1.3
3      1.5
4      1.4
      ... 
145    5.2
146    5.0
147    5.2
148    5.4
149    5.1
Name: petal_length, Length: 150, dtype: float64

In [0]:
petalLengthSeries+10

0      11.4
1      11.4
2      11.3
3      11.5
4      11.4
       ... 
145    15.2
146    15.0
147    15.2
148    15.4
149    15.1
Name: petal_length, Length: 150, dtype: float64

In [0]:
petalLengthSeries

0      1.4
1      1.4
2      1.3
3      1.5
4      1.4
      ... 
145    5.2
146    5.0
147    5.2
148    5.4
149    5.1
Name: petal_length, Length: 150, dtype: float64

In [0]:
data = pd.Series([5, 2, 3,7], index=['a', 'b', 'c', 'd'])
data1 = pd.Series([1, 6, 4, 9], index=['a', 'b', 'd', 'e'])
pd.concat([data1,data],axis=1)

0 
 1 
 
 
 
 
 a 
 1.0 
 5.0 
 
 
 b 
 6.0 
 2.0 
 
 
 d 
 4.0 
 7.0 
 
 
 e 
 9.0 
 NaN 
 
 
 c 
 NaN 
 3.0

In [0]:
pd.concat([data1,data],axis=0)

a    1
b    6
d    4
e    9
a    5
b    2
c    3
d    7
dtype: int64